from datetime import date, timedelta
import random
from typing import Optional

from fastapi import APIRouter, Depends
from pydantic import BaseModel

from app.core.deps import get_optional_user
from app.models.user import User

router = APIRouter(prefix="/studyplan", tags=["studyplan"])

# ── Static month timeline ─────────────────────────────────────────────────────
MONTHLY_PLAN = [
    {"month": 1,  "label": "January",   "focus": "Foundation & Self-Assessment",    "tasks": ["Take a baseline mock test", "Build daily reading habit (Dawn editorial)", "Start English grammar review"]},
    {"month": 2,  "label": "February",  "focus": "Islamic Studies & Essay Writing", "tasks": ["Complete Islamic Studies syllabus", "Practice one essay per week", "English precis daily practice"]},
    {"month": 3,  "label": "March",     "focus": "Pakistan Affairs",                "tasks": ["Constitutional history 1947–present", "Foreign policy & CPEC", "Pakistan geography & resources"]},
    {"month": 4,  "label": "April",     "focus": "Current Affairs Intensive",       "tasks": ["Daily Dawn editorial + notes", "Monthly current affairs digest", "MCQ practice 20/day"]},
    {"month": 5,  "label": "May",       "focus": "General Science & Ability",       "tasks": ["Science fundamentals (Physics, Chemistry, Bio)", "Math & analytical reasoning", "Mental ability practice tests"]},
    {"month": 6,  "label": "June",      "focus": "Optionals — Part 1",              "tasks": ["Begin first two optional subjects", "Complete one optional fully", "Compulsory quick revision"]},
    {"month": 7,  "label": "July",      "focus": "Optionals — Part 2",              "tasks": ["Remaining optional subjects", "Past paper topic analysis", "Time-management practice"]},
    {"month": 8,  "label": "August",    "focus": "Intensive Revision",              "tasks": ["Full syllabus rapid revision", "Essay writing 2× per week", "Mock tests every weekend"]},
    {"month": 9,  "label": "September", "focus": "Past Papers Sprint",              "tasks": ["Solve last 5 years past papers", "Focus exclusively on weak areas", "Speed & accuracy drills"]},
    {"month": 10, "label": "October",   "focus": "Final Revision",                  "tasks": ["Compact notes review", "Current affairs final update", "Mental health & energy management"]},
    {"month": 11, "label": "November",  "focus": "Exam Simulation",                 "tasks": ["Full-length timed exams daily", "Stress management techniques", "Final weak-area blitz"]},
    {"month": 12, "label": "December",  "focus": "Consolidation & Rest",            "tasks": ["Light revision only", "Stay updated on breaking news", "Rest and mental wellness"]},
]

# ── Subject task categories ───────────────────────────────────────────────────
_WRITING_SUBJECTS  = {"Essay", "English (Precis & Composition)"}
_NUMERICAL_SUBJECTS = {
    "General Science & Ability", "Statistics", "Pure Mathematics",
    "Applied Mathematics", "Accounting & Auditing", "Computer Science",
}
_LANGUAGE_SUBJECTS = {
    "English Literature", "Urdu", "Arabic", "Persian",
    "Journalism & Mass Communication",
}
# Everything else → analytical

# ── Category task templates ───────────────────────────────────────────────────
_WRITING_TASKS: dict[str, list[str]] = {
    "Beginner": [
        "Read 2 model CSS answers on {topic} — note structure and language",
        "Write a detailed bullet-point outline for {topic}",
        "Collect 5 relevant facts, quotes or statistics for {topic}",
        "Practice writing the introduction paragraph for {topic}",
        "List key arguments for {topic} with supporting evidence",
    ],
    "Intermediate": [
        "Write a 600-word timed response on {topic} in 45 minutes",
        "Analyse a CSS model answer on {topic} — identify thesis and arguments",
        "Practice three different introduction styles for {topic}",
        "Compile expert quotes and real-world examples for {topic}",
        "Write and self-evaluate a conclusion for {topic}",
    ],
    "Advanced": [
        "Write a full 1000-word CSS-standard essay on {topic} under timed conditions",
        "Solve last 5 years CSS past paper questions on {topic}",
        "Critically evaluate multiple perspectives on {topic}",
        "Self-grade your response using CSS examiner criteria for {topic}",
        "Argue both sides analytically, citing data and case studies on {topic}",
    ],
}

_ANALYTICAL_TASKS: dict[str, list[str]] = {
    "Beginner": [
        "Read the prescribed text section on {topic} and take structured notes",
        "Write a one-page summary of key points in {topic}",
        "Solve 10 CSS past-paper MCQs on {topic}",
        "List the 8 most important facts or arguments about {topic}",
        "Draw a concept map linking key ideas in {topic}",
    ],
    "Intermediate": [
        "Make analytical notes on {topic} using headings and sub-points",
        "Solve a CSS past-paper essay question on {topic}",
        "Write a 250-word critical analysis of {topic}",
        "Compare two contrasting viewpoints on {topic} in tabular form",
        "Prepare a timeline or cause-effect diagram for {topic}",
    ],
    "Advanced": [
        "Solve 2 CSS past-paper long-answer questions on {topic}",
        "Write a comprehensive analytical essay on {topic}",
        "Critically evaluate competing theories and evidence on {topic}",
        "Identify gaps in standard analysis of {topic} and propose original insights",
        "Prepare a compact revision card with key arguments for {topic}",
    ],
}

_NUMERICAL_TASKS: dict[str, list[str]] = {
    "Beginner": [
        "Study theory and key formulas for {topic}",
        "Solve 10 basic practice problems on {topic}",
        "Read worked examples and replicate them for {topic}",
        "Create a formula sheet and key definitions for {topic}",
        "Identify common mistake areas when solving {topic}",
    ],
    "Intermediate": [
        "Solve 15 medium-difficulty problems on {topic}",
        "Attempt CSS past-paper numerical questions on {topic}",
        "Review worked examples then solve 10 similar problems on {topic}",
        "Timed drill — solve 10 problems on {topic} in 20 minutes",
        "Identify and correct your error patterns in {topic}",
    ],
    "Advanced": [
        "Solve CSS past-paper full section on {topic} under timed conditions",
        "Solve 20 advanced problems including proofs/derivations on {topic}",
        "Create a self-test of 10 problems on {topic} and mark against solutions",
        "Revise {topic} end-to-end: theory → examples → past paper",
        "Attempt last 5 years CSS numerical questions on {topic}",
    ],
}

_LANGUAGE_TASKS: dict[str, list[str]] = {
    "Beginner": [
        "Read selected text on {topic} and note new vocabulary",
        "Identify key literary or linguistic features in {topic}",
        "Translate or paraphrase a key passage from {topic}",
        "Write a brief response paragraph on {topic}",
        "Build a vocabulary list of 10 key terms from {topic}",
    ],
    "Intermediate": [
        "Write a critical appreciation of the text on {topic}",
        "Compare the treatment of {topic} across two different works",
        "Solve CSS comprehension questions from past papers on {topic}",
        "Practise translation exercises related to {topic}",
        "Write an essay or critique on {topic} using textual evidence",
    ],
    "Advanced": [
        "Write a detailed literary or linguistic analysis of {topic}",
        "Solve full CSS past-paper language questions on {topic}",
        "Compare primary texts with critical commentary on {topic}",
        "Write a research-quality short essay on {topic}",
        "Evaluate the significance of {topic} in its broader tradition",
    ],
}

_REVISION_ACTIVITY_SETS = [
    "Re-read all concise notes and highlight key points | Solve 15 CSS past-paper MCQs",
    "Create a one-page mind-map of all major topics | Attempt 2 CSS long-answer questions",
    "Solve a timed 1-hour mock paper section | Self-grade using CSS marking scheme",
    "Revise weak areas identified in practice | Attempt short-answer questions from past 5 years",
    "Make flash cards for key definitions and facts | Quick-fire Q&A self-test",
    "Re-read all summary notes | Solve past-paper analytical questions under timed conditions",
    "Attempt a full past paper under exam conditions | Analyse and note every error",
]

# ── Comprehensive CSS syllabus topics (30+ per subject) ──────────────────────
SUBJECT_TOPICS: dict[str, list[str]] = {

    "Essay": [
        "Essay Structure — Introduction, Body & Conclusion",
        "Argument Building & Logical Flow",
        "Thesis Statement & Proposition Writing",
        "Evidence, Examples & Data in Essays",
        "Transitional Phrases & Coherence",
        "Introduction Techniques — Hook, Background, Thesis",
        "Conclusion Techniques — Synthesis & Call to Action",
        "Essay Outline Planning Under Timed Conditions",
        "Democracy, Governance & Political Reforms",
        "Economic Development & Poverty Alleviation",
        "Education — Challenges & Reforms in Pakistan",
        "Climate Change, Environment & Sustainability",
        "Science, Technology & Artificial Intelligence",
        "Social Media & Digital Transformation",
        "Women's Empowerment & Gender Equality",
        "Pakistan's Foreign Policy & Global Role",
        "Youth, Unemployment & Brain Drain",
        "Corruption, Accountability & Rule of Law",
        "Water Crisis & Food Security",
        "Health, Pandemics & Public Health Policy",
        "Media, Press Freedom & Responsible Journalism",
        "Human Rights & Civil Liberties",
        "Extremism, Terrorism & Counter-Narratives",
        "Agriculture & Rural Development",
        "Urbanisation & Smart Cities",
        "CPEC & Regional Connectivity",
        "Justice System & Judicial Reforms",
        "Religion & State — A Balanced Perspective",
        "Globalisation & Developing Nations",
        "Vocabulary & Diction Enrichment Practice",
        "Full Timed Essay Practice — Social Theme",
        "Full Timed Essay Practice — Political Theme",
        "Full Timed Essay Practice — Economic Theme",
        "Self-Review & Peer Evaluation of Essays",
        "Past Paper Essay Questions — Analysis & Planning",
    ],

    "English (Precis & Composition)": [
        "Précis Writing — Rules, Steps & Technique",
        "Dawn Editorial Précis Practice — Set 1",
        "Dawn Editorial Précis Practice — Set 2",
        "Comprehension — Inference & Critical Reading",
        "Grammar — Subject-Verb Agreement",
        "Grammar — Tenses & Verb Forms",
        "Grammar — Articles, Prepositions & Conjunctions",
        "Sentence Correction — Common CSS Errors",
        "Vocabulary — Root Words, Prefixes & Suffixes",
        "Vocabulary — Synonyms, Antonyms & Context",
        "Idioms, Phrases & Phrasal Verbs",
        "Paragraph Writing — Unity & Coherence",
        "Formal Letter Writing — Official & Semi-Official",
        "Application & Job Letter Writing",
        "Report Writing — Structure & Format",
        "Summarisation Techniques",
        "Punctuation — Semicolons, Colons & Dashes",
        "Sentence Variety & Style",
        "Passive to Active Voice Transformation",
        "Direct & Indirect Speech",
        "Figures of Speech in Context",
        "Essay Composition Practice",
        "Comprehension Passage — Science Text",
        "Comprehension Passage — Social & Political Text",
        "Translation — Urdu to English",
        "Error Identification Exercises",
        "Use of Connectives & Discourse Markers",
        "Précis Revision — Speed & Accuracy Drill",
        "CSS Paper Pattern — Full Practice Test",
    ],

    "General Science & Ability": [
        "Number Systems — Natural, Integer, Rational & Real",
        "Basic Arithmetic — HCF, LCM & Fractions",
        "Algebra — Equations, Inequalities & Polynomials",
        "Ratio, Proportion & Percentage Problems",
        "Geometry — Lines, Angles, Triangles & Circles",
        "Statistics & Data Interpretation — Tables & Graphs",
        "Probability & Basic Combinatorics",
        "Sequence, Series & Number Patterns",
        "Physics — Mechanics: Force, Motion & Newton's Laws",
        "Physics — Work, Energy, Power & Simple Machines",
        "Physics — Heat, Temperature & Thermodynamics",
        "Physics — Light: Reflection, Refraction & Optics",
        "Physics — Electricity & Magnetism",
        "Physics — Waves, Sound & Vibration",
        "Chemistry — Atomic Structure & Periodic Table",
        "Chemistry — Chemical Bonding & Reactions",
        "Chemistry — Acids, Bases, Salts & pH",
        "Chemistry — Organic Chemistry Basics",
        "Biology — Cell Structure & Cell Division",
        "Biology — Genetics, DNA & Heredity",
        "Biology — Human Digestive & Respiratory Systems",
        "Biology — Human Circulatory & Nervous Systems",
        "Biology — Ecology, Environment & Food Chains",
        "Computer Basics — Hardware, Software & Internet",
        "Everyday Science — Scientific Phenomena in Daily Life",
        "Logical Reasoning & Verbal Ability",
        "Analytical Reasoning — Puzzles & Pattern Recognition",
        "Mental Ability — Data Sufficiency & Critical Thinking",
        "General Ability Mock Test Practice",
    ],

    "Pakistan Affairs": [
        "Two-Nation Theory & Ideology of Pakistan",
        "Sir Syed Ahmed Khan & the Aligarh Movement",
        "Allama Iqbal — Philosophy & Vision of Pakistan",
        "Quaid-e-Azam — Life, Leadership & Vision",
        "Lahore Resolution 1940 & Its Significance",
        "Muslim League & the Pakistan Movement 1906–1947",
        "Partition 1947 — Plan, Process & Aftermath",
        "Early Administrative & Political Challenges 1947–1956",
        "Constitution of 1956 — Features & Failure",
        "Ayub Khan Era — SEATO, CENTO & Basic Democracies",
        "1965 War — Causes, Events & Impact",
        "Constitution of 1962 & Political Developments",
        "1970 Elections & Road to the Fall of Dhaka",
        "1971 War — Causes, Events & Lessons",
        "Bhutto Era — Constitution of 1973 & Nationalization",
        "Zia-ul-Haq Era — Islamisation & Afghan War",
        "Restoration of Democracy 1988–1999",
        "Musharraf Era — Enlightened Moderation & 9/11",
        "18th Constitutional Amendment — Devolution of Power",
        "25th Amendment & FATA Merger",
        "Pakistan-China Strategic Partnership & CPEC",
        "Pakistan-India Relations — Kashmir & Core Issues",
        "Pakistan-Afghanistan Relations & Taliban Factor",
        "Pakistan-US Relations — History & Dynamics",
        "Pakistan & the Muslim World — OIC & Gulf Relations",
        "Pakistan's Nuclear Programme & Security Doctrine",
        "Economy of Pakistan — Structural Issues & IMF",
        "Agriculture & Water Crisis — Indus Waters Treaty",
        "Education System — Issues & Reform Agenda",
        "Federalism & Provincial Autonomy — NFC Award",
        "Judiciary — Judicial Independence & Activism",
        "Civil-Military Relations in Pakistan",
        "Media, Civil Society & Democracy",
        "Climate Change — Pakistan's Vulnerability & Floods",
        "Terrorism, Extremism & NACTA Strategy",
        "Youth, Unemployment & Human Development",
        "Geopolitical Significance of Pakistan",
    ],

    "Islamic Studies": [
        "Six Articles of Faith (Arkan-e-Iman)",
        "Five Pillars — Shahadah & Salah in Detail",
        "Five Pillars — Zakah, Sawm & Hajj",
        "Introduction to the Holy Quran — Revelation & Compilation",
        "Surah Al-Baqarah — Key Themes & Legal Verses",
        "Selected Surahs — Al-Imran, An-Nisa & Al-Maidah",
        "Quranic Sciences — Tafsir, Tajweed & Nuzul",
        "Hadith Sciences — Classification & Authenticity",
        "Major Hadith Collections — Bukhari, Muslim & Tirmizi",
        "Selected 40 Nawawi Hadith — Study & Commentary",
        "Seerah — Early Life, Revelation & Makkan Period",
        "Seerah — Hijrah & Establishment of Madinah State",
        "Seerah — Major Battles & Conquest of Makkah",
        "Seerah — Final Years, Khutba Hajja & Death",
        "Khulafa-e-Rashideen — Abu Bakr & Umar (RA)",
        "Khulafa-e-Rashideen — Uthman & Ali (RA)",
        "Umayyad & Abbasid Caliphates — Overview",
        "Islamic Jurisprudence (Fiqh) — Sources & Four Schools",
        "Islamic Economic System — Riba, Zakah & Waqf",
        "Social System in Islam — Family, Marriage & Divorce",
        "Political System in Islam — Shura & Khilafah",
        "Women's Rights in Islam — Quranic Perspective",
        "Islamic Civilization — Science, Art & Architecture",
        "Contemporary Muslim Issues — Unity & OIC",
        "Islam & Democracy — Compatibility Debate",
        "Islamophobia & Muslim World Image",
        "Islamic Ethics — Akhlaq & Social Responsibility",
        "Pakistan as an Islamic State — Constitutional Basis",
    ],

    "Current Affairs": [
        "Pakistan Political Developments — Parties & Elections",
        "Federal Budget Analysis — Key Measures & Impact",
        "State Bank & Monetary Policy — IMF Programme Conditions",
        "Pakistan's External Debt & Balance of Payments",
        "CPEC Phase II — Projects, Delays & Progress",
        "Pakistan-India Relations — Current Diplomatic Status",
        "Pakistan-Afghanistan — Taliban & Border Issues",
        "China-US Competition & Pakistan's Balancing Act",
        "Russia-Ukraine War — Global & Regional Impacts",
        "Israel-Palestine Conflict & Muslim World Response",
        "SAARC — Dysfunction & Alternative Frameworks",
        "SCO — Pakistan's Membership & Dividends",
        "United Nations — Reform Debate & Pakistan's Role",
        "Climate Change — COP Outcomes & Pakistan Floods",
        "Water Crisis — Indus Waters Treaty Dispute",
        "Global Terrorism — ISIS, TTP & Counter-Terrorism",
        "Nuclear Proliferation — IAEA & NPT Issues",
        "Artificial Intelligence — Global Race & Ethics",
        "Social Media Laws & Digital Rights",
        "Gender Issues & Women's Rights in Pakistan",
        "Education Emergency — Out-of-School Children",
        "Public Health — Polio, Dengue & Health Systems",
        "Agriculture & Food Security Crisis",
        "Afghan Refugees — Pakistan's Humanitarian Burden",
        "Election Reforms & Digital Voting Debate",
        "Anti-Corruption — NAB & Accountability Framework",
        "Saudi Arabia Vision 2030 & Gulf Dynamics",
        "Iran — Nuclear Deal & Regional Influence",
        "Current Affairs MCQ Sprint — National Issues",
        "Current Affairs MCQ Sprint — International Issues",
    ],

    "International Relations": [
        "Classical Realism — Morgenthau & Power Politics",
        "Structural Realism — Waltz & Balance of Power",
        "Liberalism & Neoliberal Institutionalism",
        "Constructivism — Wendt & the Social Construction of IR",
        "Post-Colonialism & Critical IR Theory",
        "Feminist Perspectives in IR",
        "State Sovereignty & Non-Interference Principle",
        "National Interest & Foreign Policy Decision-Making",
        "Diplomacy — Types, Tools & Modern Track-II Practices",
        "International Law — Sources, Subjects & Enforcement",
        "United Nations System — Charter, Organs & Reform",
        "International Political Economy — Trade & Finance",
        "South Asia — SAARC, Conflicts & Regional Order",
        "China's Rise — BRI & Great Power Competition",
        "US Foreign Policy — Hegemony, Decline & Indo-Pacific",
        "Russia — Resurgence, Ukraine & Multipolarity",
        "Middle East — Instability & Great Power Rivalry",
        "European Union — Integration, Brexit & Challenges",
        "Pakistan's Foreign Policy — Priorities & Challenges",
        "Pakistan-China — All-Weather Strategic Partnership",
        "Pakistan-US — Aid, Drones & Strategic Divergence",
        "Pakistan-India — Kashmir, LoC & Normalization",
        "Pakistan-Afghanistan — Strategic Depth Revisited",
        "Pakistan's Nuclear Posture & Deterrence",
        "Global Terrorism & Counter-Terrorism Frameworks",
        "Climate Diplomacy & COP Negotiations",
        "International Human Rights Law & Practice",
        "UN Peacekeeping — Pakistan's Contribution",
        "Cyber Security & Digital Warfare in IR",
        "Globalisation — Benefits, Backlash & Deglobalisation",
    ],

    "Political Science": [
        "Plato's Republic — Justice & the Ideal State",
        "Aristotle — Politics & Classification of Constitutions",
        "Machiavelli — The Prince & Political Realism",
        "Hobbes — Leviathan & the Social Contract",
        "Locke — Natural Rights, Consent & Liberalism",
        "Rousseau — General Will & Democratic Theory",
        "Montesquieu — Separation of Powers & Federalism",
        "Bentham & Mill — Utilitarianism & Liberty",
        "Marx & Engels — Historical Materialism & Class Struggle",
        "Gramsci — Hegemony & Civil Society",
        "Contemporary Liberalism — Rawls & Dahl",
        "Sovereignty — Internal, External & Popular",
        "State — Origins, Functions & Theories",
        "Government — Presidential vs Parliamentary Systems",
        "Democracy — Liberal, Direct & Participatory Types",
        "Federalism — Theory, Models & Pakistan's Case",
        "Constitutionalism & Rule of Law",
        "Political Parties — Functions, Types & Systems",
        "Electoral Systems — FPTP, PR & Mixed Systems",
        "Civil Society & NGOs in Democratic Politics",
        "Public Opinion, Political Culture & Participation",
        "Nationalism — Classical & Contemporary Forms",
        "Imperialism & Neo-Colonialism",
        "Welfare State — Origins, Crisis & Future",
        "Political Development in Pakistan",
        "Civil-Military Relations in Pakistan",
        "Political Parties in Pakistan — PPP, PML-N & PTI",
        "Local Government — Theory & Pakistan Practice",
        "Judicial Activism & Politics in Pakistan",
        "Human Rights & Political Freedom",
    ],

    "Sociology": [
        "Auguste Comte — Positivism & the Science of Society",
        "Emile Durkheim — Social Facts, Solidarity & Suicide",
        "Max Weber — Social Action, Bureaucracy & Rationalization",
        "Karl Marx — Alienation, Class Conflict & Revolution",
        "Talcott Parsons — Structural Functionalism & AGIL",
        "Conflict Theory & Symbolic Interactionism",
        "Social Groups — Primary, Secondary & Reference Groups",
        "Social Institution — Family: Types & Functions",
        "Social Institution — Religion: Durkheim & Weber",
        "Social Institution — Education: Functionalist & Conflict",
        "Social Stratification — Class, Caste & Status",
        "Social Mobility — Types, Determinants & Measurement",
        "Culture — Components, Ethnocentrism & Cultural Relativism",
        "Socialisation — Agents, Stages & Resocialisation",
        "Deviance — Anomie, Strain & Labelling Theories",
        "Social Control — Formal & Informal Mechanisms",
        "Poverty & Inequality in Pakistan",
        "Gender Inequality & Patriarchy in Pakistani Society",
        "Urbanisation & Rural-Urban Migration",
        "Population Dynamics & Demographic Transition",
        "Social Change — Causes, Resistance & Revolution",
        "Globalisation & Cultural Change",
        "Social Problems in Pakistan — Crime, Drugs & Bonded Labour",
        "Religious Extremism — Sociological Perspective",
        "Social Research Methods — Quantitative Approaches",
        "Social Research Methods — Qualitative & Ethnography",
        "Survey Design, Sampling & Data Collection",
        "Data Analysis & Sociological Interpretation",
        "Contemporary Sociology — Post-Modern & Digital Society",
    ],

    "Economics": [
        "Demand Analysis — Law, Curves & Price Elasticity",
        "Income & Cross Elasticity of Demand",
        "Supply Analysis — Law, Shifts & Elasticity",
        "Consumer Equilibrium — Utility & Indifference Curve",
        "Production — Short Run, Long Run & Returns to Scale",
        "Cost Theory — Fixed, Variable, AC, MC & Cost Curves",
        "Perfect Competition — Equilibrium & Efficiency",
        "Monopoly — Price-Output Decision & Deadweight Loss",
        "Oligopoly & Monopolistic Competition",
        "Factor Markets — Labour, Capital & Land",
        "National Income — GDP, GNP & Measurement Methods",
        "Consumption, Savings & Investment Functions",
        "Keynesian Economics — Multiplier & Accelerator",
        "Money — Functions, Quantity Theory & Demand",
        "Banking System — Commercial Banks & Central Banking",
        "Inflation — Types, Causes, Phillips Curve & Control",
        "Unemployment — Types, Theories & Natural Rate",
        "IS-LM Model & Aggregate Demand-Supply Framework",
        "Fiscal Policy — Tools, Crowding Out & Effectiveness",
        "Monetary Policy — Tools, Transmission & Limitations",
        "International Trade — Comparative Advantage & HO Theory",
        "Balance of Payments — Current & Capital Account",
        "Exchange Rate — Systems, Determination & PPP",
        "WTO — Principles, Trade Rounds & Pakistan",
        "Economic Development vs Economic Growth",
        "Development Theories — Rostow, Lewis & Amartya Sen",
        "Public Finance — Taxation Principles & Pakistan FBR",
        "Pakistan Economy — Structural Issues & Challenges",
        "IMF Programmes & Pakistan — Conditionalities",
        "Islamic Economics — Riba-Free Banking & Sukuk",
        "CPEC — Economic Impact & Debt Concerns",
        "Agricultural Economics & Rural Development in Pakistan",
    ],

    "Public Administration": [
        "Scientific Management — F.W. Taylor's Principles",
        "Administrative Management — Fayol's 14 Principles",
        "Bureaucracy — Max Weber's Ideal Type",
        "POSDCORB — Luther Gulick's Administrative Framework",
        "Human Relations School — Elton Mayo & Hawthorne",
        "Maslow's Hierarchy of Needs & Motivation",
        "McGregor's Theory X & Y",
        "Herzberg's Two-Factor Theory",
        "Systems Approach — Open Systems & Cybernetics",
        "New Public Management — Market-Oriented Reforms",
        "Good Governance — UNDP's 8 Characteristics",
        "E-Government — Digital Transformation in Public Sector",
        "Organisational Structures — Hierarchy vs Flat",
        "Leadership Styles in Public Organisations",
        "Decision-Making — Rational, Bounded & Incremental Models",
        "Communication in Organisations — Formal & Informal",
        "Budgeting Systems — Line-Item, Programme & Zero-Based",
        "Financial Administration — Audit & Accountability",
        "Personnel Administration — Recruitment, Merit & Promotion",
        "Training & Capacity Building in Civil Services",
        "Administrative Law — Delegated Legislation & Tribunals",
        "Civil Service of Pakistan — Structure & CSS Reforms",
        "Federal Government — Cabinet, Ministries & Divisions",
        "Provincial Administration & District Government",
        "Local Government in Pakistan — History & Current Status",
        "Public Policy Analysis — Rational & Incremental Models",
        "Policy Implementation — Challenges in Pakistan",
        "Accountability Mechanisms — NAB, FIA & Ombudsman",
        "Administrative Reforms in Pakistan — History & Agenda",
        "Comparative Public Administration — UK, US & NPM",
    ],

    "Constitutional Law": [
        "Constitutional Law — Nature, Sources & Classification",
        "Constitutionalism — Historical Development & Rule of Law",
        "Supremacy of Constitution & Basic Structure Doctrine",
        "Preamble & Objectives Resolution 1949 — Legal Effect",
        "Fundamental Rights — Articles 8–28 (Overview)",
        "Right to Equality — Articles 25, 26 & 27",
        "Freedom of Speech, Association & Assembly — Arts 19–20",
        "Right to Life, Liberty & Due Process — Arts 9–10A",
        "Freedom of Religion — Articles 20–22",
        "Principles of Policy — Arts 29–40 & Justiciability",
        "Federal Structure — Lists I, II & Concurrent",
        "18th Amendment — Provincial Autonomy & Devolution",
        "Parliament — National Assembly & Senate Composition",
        "Parliamentary Procedure — Legislation & Money Bills",
        "Speaker, Deputy Speaker & Parliamentary Privileges",
        "President — Election, Powers & Removal",
        "Prime Minister — Appointment, Functions & Vote of No Confidence",
        "Federal Cabinet — Composition & Collective Responsibility",
        "Supreme Court — Original & Appellate Jurisdiction (Art 184–188)",
        "High Courts — Constitution, Powers & Writ Jurisdiction",
        "Judicial Review & Judicial Independence",
        "Federal Shariat Court — Jurisdiction & Powers",
        "Financial Provisions — NFC Award & Federal Consolidated Fund",
        "Emergency Provisions — Arts 232–237 & Fundamental Rights",
        "Constitutional Amendments — 1st to 26th (Key Ones)",
        "Elections Commission — Independence & Powers",
        "Federal Service Commission — Functions & Safeguards",
        "Local Government — Constitutional Basis (Art 140A)",
        "Comparative Constitutional Law — UK, USA & India",
        "Contemporary Constitutional Issues in Pakistan",
    ],

    "Geography": [
        "Geomorphology — Internal & External Forces, Landforms",
        "Plate Tectonics — Theory, Types & Seismic Activity",
        "River Systems — Drainage Patterns & Erosion-Deposition",
        "Climate Systems — Factors, Elements & Global Patterns",
        "Climatology — Koppen Classification & World Climates",
        "Ocean Systems — Currents, Tides & Maritime Zones",
        "Soil — Types, Formation, Profiles & Degradation",
        "Natural Vegetation — Biomes, Forests & Grasslands",
        "World Population — Distribution, Growth & Demographic Transition",
        "Migration — Causes, Types & Global Patterns",
        "Urban Geography — City Models, Growth & Urban Issues",
        "Rural Geography — Settlement Patterns & Agricultural Land Use",
        "Natural Resources — Renewable & Non-Renewable Types",
        "Agriculture — Farming Systems & World Distribution",
        "Industry — Location Theories, Types & Industrial Regions",
        "Trade & Transport — Modes, Routes & Globalisation",
        "Energy Resources — Fossil Fuels vs Renewables",
        "Political Geography — State, Boundaries & Geopolitics",
        "Geopolitics — Mackinder, Spykman & Contemporary Theories",
        "Physical Geography of Pakistan — Relief & Drainage",
        "Provinces & Administrative Regions of Pakistan",
        "Rivers of Pakistan — Indus System & Water Issues",
        "Agriculture in Pakistan — Crops, Irrigation & Issues",
        "Minerals & Energy Resources of Pakistan",
        "Population Geography of Pakistan — Census & Urbanisation",
        "Major Urban Centres of Pakistan — Karachi, Lahore, Islamabad",
        "Environmental Degradation — Deforestation & Desertification",
        "GIS & Remote Sensing — Applications",
        "Climate Change — Geographic Dimensions & Pakistan Floods",
        "Sustainable Development & Environmental Management",
    ],

    "Journalism & Mass Communication": [
        "Communication Process — Elements, Models & Barriers",
        "Agenda-Setting Theory — McCombs & Shaw",
        "Framing Theory & Media Framing",
        "Uses & Gratifications Theory",
        "Cultivation Theory & Media Effects Research",
        "Two-Step Flow & Opinion Leadership Theory",
        "News Values — What Makes News?",
        "News Writing — Inverted Pyramid, Leads & 5Ws",
        "Feature Writing — Types & Techniques",
        "Investigative Reporting — Methods & Ethics",
        "Editorial Writing & Opinion Journalism",
        "Newspaper Production — Layout, Design & Editing",
        "Radio Journalism — Scripting & Production",
        "Television Journalism — Package, Bulletin & Live Reporting",
        "Broadcast News Ethics & Standards",
        "Digital Media — New Media Landscape & Disruption",
        "Social Media Journalism — Opportunities & Risks",
        "Data Journalism & Infographic Storytelling",
        "Citizen Journalism & Crowdsourcing News",
        "Media Laws in Pakistan — PEMRA, PPRA & PTA",
        "Freedom of Press — Constitutional & Legal Framework",
        "Media Ethics — Codes of Conduct & Ethical Dilemmas",
        "Defamation, Privacy & Contempt of Court",
        "Public Relations — Principles, Models & Practice",
        "Advertising — Creative Brief, Campaigns & Ethics",
        "Media Research Methods — Content Analysis & Surveys",
        "Media Economics & Business Models",
        "Development Communication — Communication for Change",
        "International Communication & Global Media",
        "Media & National Security — Responsibilities & Limits",
        "Contemporary Challenges in Pakistani Media",
    ],

    "Psychology": [
        "History of Psychology — Schools of Thought",
        "Research Methods — Experiments, Surveys & Case Studies",
        "Biological Bases of Behaviour — Neurons & Brain Structure",
        "Sensation — The Five Senses & Sensory Thresholds",
        "Perception — Gestalt Principles & Perceptual Constancy",
        "States of Consciousness — Sleep Stages & REM",
        "Altered States — Dreams, Meditation & Hypnosis",
        "Classical Conditioning — Pavlov's Experiments & Applications",
        "Operant Conditioning — Skinner, Reinforcement & Punishment",
        "Observational Learning — Bandura's Bobo Doll Study",
        "Memory — Encoding, Storage & Retrieval Systems",
        "Short-Term, Long-Term & Working Memory",
        "Forgetting — Interference, Decay & Repression",
        "Thinking & Problem Solving — Heuristics & Algorithms",
        "Intelligence — Spearman's g, Gardner's Multiple Intelligences",
        "Language & Thought — Sapir-Whorf Hypothesis",
        "Motivation Theories — Drive Reduction, Maslow & Self-Determination",
        "Emotion — James-Lange, Cannon-Bard & Schachter-Singer Theories",
        "Developmental Psychology — Piaget's Four Stages",
        "Developmental Psychology — Erikson's Psychosocial Stages",
        "Attachment Theory — Bowlby & Ainsworth",
        "Personality — Freud's Psychoanalytic Theory & Defence Mechanisms",
        "Personality — Humanistic Theory — Rogers & Self-Concept",
        "Personality — Big Five Trait Model",
        "Social Psychology — Attitudes, Attribution & Attitude Change",
        "Social Psychology — Conformity (Asch) & Obedience (Milgram)",
        "Prejudice, Stereotypes & Discrimination",
        "Stress, Coping Mechanisms & Health Psychology",
        "Abnormal Psychology — DSM-5 Classification & Models",
        "Anxiety, Mood Disorders & Schizophrenia Spectrum",
        "Psychotherapy — CBT, Psychoanalytic & Humanistic Approaches",
        "Applied Psychology — Industrial, Educational & Forensic",
        "Psychology in Pakistani Context — Issues & Applications",
    ],

    "Islamic History & Culture": [
        "Pre-Islamic Arabia — Jahiliyyah, Tribes & Socio-Economic Life",
        "Prophet Muhammad (PBUH) — Early Life & First Revelation",
        "Makkan Period — Preaching, Opposition & Persecution",
        "Hijrah to Madinah & Constitution of Madinah",
        "Madinah Period — Battles of Badr, Uhud & Khandaq",
        "Treaty of Hudaibiyah & Conquest of Makkah",
        "Final Years of the Prophet — Hajj & Death",
        "Hazrat Abu Bakr Siddiq — Ridda Wars & Consolidation",
        "Hazrat Umar Farooq — Administration, Expansion & Justice",
        "Hazrat Uthman — Quran Compilation & Late Challenges",
        "Hazrat Ali — Civil Strife, Battles & Karbala",
        "Umayyad Caliphate — Muawiyah, Yazid & Administration",
        "Umayyad Expansion — Spain, Transoxiana & Sindh",
        "Battle of Tours/Poitiers & Halt of Westward Expansion",
        "Abbasid Caliphate — Rise, Golden Age & Decline",
        "Islamic Golden Age — Bayt al-Hikmah & Translation Movement",
        "Muslim Scientists — Al-Kindi, Al-Farabi, Ibn Sina, Al-Biruni",
        "Al-Ghazali, Ibn Rushd & the Philosophy Debate",
        "Fatimid, Seljuk & Ayyubid Dynasties",
        "Crusades — Causes, Major Events & Muslim Response",
        "Saladin & Reconquest of Jerusalem (1187)",
        "Muslim Spain (Al-Andalus) — Civilisation & Convivencia",
        "Mongol Invasions & Destruction of Baghdad (1258)",
        "Ottoman Empire — Rise, Expansion & Sulayman the Magnificent",
        "Mughal Empire — Babur, Humayun & Akbar's Synthesis",
        "Mughal Empire — Jahangir, Shah Jahan & Aurangzeb",
        "Islamic Art, Architecture & Cultural Contributions",
        "Decline of Muslim Power — Internal & External Factors",
        "Islamic Modernism — Al-Afghani, Abduh & Iqbal",
        "Islamic Civilisation's Legacy to Human Knowledge",
    ],

    "History of Pakistan & India": [
        "Indus Valley Civilisation — Mohenjo-Daro, Harappa & Decline",
        "Vedic Age & Early Aryan Kingdoms",
        "Mauryan Empire — Chandragupta, Ashoka & Buddhist Spread",
        "Gupta Empire — Golden Age of Hindu Culture",
        "Arab Conquest of Sindh — Muhammad bin Qasim (712 AD)",
        "Ghaznavid Invasions — Mahmud of Ghazni",
        "Ghorid Invasions & Establishment of Delhi Sultanate",
        "Delhi Sultanate — Slave, Khilji & Tughlaq Dynasties",
        "Bahmani & Regional Sultanates",
        "Babur — Foundation of Mughal Empire (1526)",
        "Akbar the Great — Administration, Din-e-Ilahi & Syncretism",
        "Jahangir & Shah Jahan — Mughal Culture & Architecture",
        "Aurangzeb — Religious Policies & Seeds of Decline",
        "Rise of Maratha Power & Regional Kingdoms",
        "European Arrival — Portuguese, Dutch, French & British",
        "Battle of Plassey (1757) & British Ascendancy",
        "East India Company — Administrative & Economic Policies",
        "War of Independence 1857 — Causes, Events & Aftermath",
        "British Raj — Administrative, Social & Economic Impact",
        "Sir Syed Ahmed Khan & the Aligarh Movement",
        "Indian National Congress (1885) & National Awakening",
        "Partition of Bengal 1905 & Swadeshi Movement",
        "All India Muslim League 1906 — Foundation & Objectives",
        "Lucknow Pact 1916 & Montagu-Chelmsford Reforms",
        "Non-Cooperation & Khilafat Movements",
        "Simon Commission & Civil Disobedience Movement",
        "Round Table Conferences & Communal Award",
        "Pakistan Resolution 1940 — Lahore",
        "Cabinet Mission Plan 1946 & Interim Government",
        "Partition Plan 1947 & the Birth of Two Nations",
    ],

    "English Literature": [
        "Old English Literature — Beowulf & Anglo-Saxon Poetry",
        "Middle English — Chaucer's Canterbury Tales",
        "Renaissance Drama — Marlowe & the University Wits",
        "Shakespeare — Major Tragedies (Hamlet, Othello, Macbeth, King Lear)",
        "Shakespeare — Comedies, Histories & Sonnets",
        "John Milton — Paradise Lost & Puritan Literature",
        "Restoration Drama & John Dryden",
        "18th Century — Alexander Pope & Neo-Classicism",
        "Jonathan Swift — Satire, Gulliver's Travels & A Modest Proposal",
        "Samuel Johnson — The Age of Reason & Lexicography",
        "The Novel — Rise with Defoe, Richardson & Fielding",
        "Romantic Poetry — Wordsworth & Coleridge (Lyrical Ballads)",
        "Romantic Poetry — Byron, Keats & Shelley",
        "Victorian Novel — Charles Dickens & Social Realism",
        "Victorian Novel — Thomas Hardy, George Eliot & Brontës",
        "Victorian Poetry — Tennyson, Browning & Arnold",
        "Oscar Wilde — Aestheticism & The Importance of Being Earnest",
        "Modernist Poetry — T.S. Eliot & 'The Waste Land'",
        "W.B. Yeats — Irish Literature, Symbolism & Late Poetry",
        "Modernist Fiction — James Joyce (Ulysses) & Virginia Woolf",
        "D.H. Lawrence — Sexuality, Class & Social Realism",
        "George Orwell — Politics, Power & Dystopian Fiction",
        "Post-Colonial Literature — Chinua Achebe & Salman Rushdie",
        "South Asian English Literature — Partition Narratives",
        "Short Story — Structure & Masters (Hemingway, Mansfield)",
        "Drama — Greek Tragedy to Modern Absurdism (Beckett)",
        "Literary Criticism — Aristotle, New Criticism & Formalism",
        "Post-Structuralism — Derrida's Deconstruction",
        "Feminist Literary Criticism — Woolf, De Beauvoir & Showalter",
        "Themes — Gender, Identity, Power & Colonialism in Texts",
        "Practical Criticism — Close Reading & Explication",
    ],

    "Business Administration": [
        "Evolution of Management Thought — Classical to Contemporary",
        "Planning — Strategic, Tactical & Operational",
        "MBO — Management by Objectives",
        "Organisational Structure — Types & Departmentation",
        "Authority, Responsibility, Delegation & Span of Control",
        "Human Resource Management — Recruitment & Selection Process",
        "Training & Development — On-Job & Off-Job Methods",
        "Performance Appraisal — Methods & 360° Feedback",
        "Leadership Theories — Trait, Behavioural & Situational",
        "Motivation in Organisations — Maslow, Herzberg & Vroom",
        "Communication — Process, Channels, Barriers & Grapevine",
        "Conflict Management & Negotiation Strategies",
        "Decision-Making — Rational Model & Group Decision-Making",
        "Marketing Concepts — Orientation & Marketing Mix (4Ps)",
        "Consumer Behaviour & Market Segmentation",
        "Product Life Cycle, New Product Development & Branding",
        "Pricing Strategies & Distribution Channel Design",
        "Promotion Mix — Advertising, Sales Promotion & PR",
        "Financial Management — Time Value of Money",
        "Financial Statement Analysis — Ratios & Interpretation",
        "Capital Budgeting — NPV, IRR & Payback Period",
        "Working Capital Management — Cash, Receivables & Inventory",
        "Operations Management — Production Planning & Control",
        "Supply Chain Management & Inventory Systems",
        "Quality Management — TQM, Six Sigma & ISO 9001",
        "Strategic Management — SWOT, PESTLE & Porter's Five Forces",
        "Corporate Social Responsibility & Business Ethics",
        "Entrepreneurship — Opportunity Recognition & Business Plan",
        "International Business — FDI, MNCs & Globalisation",
        "E-Commerce & Digital Marketing",
        "Business Law in Pakistan — Contracts & Companies Act",
    ],

    "Accounting & Auditing": [
        "Accounting Concepts, Principles & GAAP",
        "Double-Entry System — Debits, Credits & Journal Entries",
        "Ledger Posting, Trial Balance & Errors",
        "Bank Reconciliation Statement",
        "Income Statement — Trading, P&L & Preparation",
        "Balance Sheet — Structure, Components & Analysis",
        "Cash Flow Statement — Direct & Indirect Methods",
        "Depreciation — SLM, WDV, Sum-of-Years & Units of Production",
        "Inventory Valuation — FIFO, LIFO & Weighted Average",
        "Partnership Accounts — Formation, Admission & Retirement",
        "Company Accounts — Share Capital & Debentures",
        "Cost Accounting — Elements, Classification & Flow",
        "Job Costing & Process Costing",
        "Marginal Costing & Break-Even Analysis",
        "Standard Costing — Setting Standards & Variance Analysis",
        "Management Accounting — Budgeting & Flexible Budgets",
        "Activity-Based Costing (ABC) — Concept & Application",
        "Auditing — Concepts, Objectives & Types",
        "Auditing Standards — ISA & National Standards",
        "Internal Audit vs External Audit",
        "Audit Planning — Risk Assessment & Materiality",
        "Audit Evidence — Procedures, Sufficiency & Reliability",
        "Internal Control Systems — COSO Framework",
        "Audit Report — Types, Qualifications & Emphasis of Matter",
        "Taxation in Pakistan — Income Tax Ordinance 2001",
        "Sales Tax Act 1990 & Federal Excise Duty",
        "Corporate Governance — SECP Regulations",
        "Financial Analysis — Ratio Analysis & Trend",
        "IFRS — Key Standards (IFRS 9, 15, 16)",
        "Ethics in Accounting — ICAP Code & Independence",
        "Government Accounting — AGP & Public Sector Audit",
    ],

    "Statistics": [
        "Data — Types, Collection Methods & Presentation",
        "Frequency Distribution — Cumulative & Relative",
        "Graphical Representation — Histogram, Ogive & Pie Chart",
        "Measures of Central Tendency — Mean, Median & Mode",
        "Measures of Dispersion — Range, Variance & Standard Deviation",
        "Quartiles, Percentiles & Box-Plot",
        "Skewness & Kurtosis — Measures & Interpretation",
        "Probability — Classical, Relative & Axiomatic",
        "Addition & Multiplication Rules, Conditional Probability",
        "Bayes' Theorem & Applications",
        "Random Variables — Discrete & Continuous",
        "Binomial Distribution — PMF, Mean & Variance",
        "Poisson Distribution — Derivation & Applications",
        "Normal Distribution — Properties & Z-Score",
        "t-Distribution, Chi-Square & F-Distribution",
        "Sampling Theory — Types of Sampling Methods",
        "Sampling Distributions — Central Limit Theorem",
        "Point Estimation — Properties of Estimators",
        "Interval Estimation — Confidence Intervals",
        "Hypothesis Testing — Framework, Type I & II Errors",
        "Z-Test & t-Test — One & Two Sample",
        "Chi-Square Test — GOF & Independence",
        "Analysis of Variance — One-Way & Two-Way ANOVA",
        "Non-Parametric Tests — Mann-Whitney & Kruskal-Wallis",
        "Correlation — Pearson & Spearman Coefficients",
        "Simple Linear Regression — OLS Estimation",
        "Multiple Regression & Model Adequacy",
        "Time Series — Trend, Seasonality & Forecasting",
        "Index Numbers — Laspeyres, Paasche & Fisher",
        "Vital Statistics — Mortality, Fertility & Life Tables",
        "Statistical Quality Control — Control Charts",
        "CSS Past Paper Statistical Problems — Practice Set",
    ],

    "Computer Science": [
        "Number Systems — Binary, Octal & Hexadecimal Conversions",
        "Boolean Algebra, Logic Gates & Digital Circuits",
        "Computer Architecture — CPU, Memory & I/O Devices",
        "Operating Systems — Functions, Types & Architecture",
        "Process Management — Scheduling, Threads & Deadlock",
        "Memory Management — Paging, Segmentation & Virtual Memory",
        "File Systems — FAT, NTFS & ext4",
        "Data Structures — Arrays, Stacks & Queues",
        "Data Structures — Linked Lists, Trees & Binary Search Trees",
        "Data Structures — Graphs, Heaps & Hash Tables",
        "Algorithm Analysis — Big O, Time & Space Complexity",
        "Sorting Algorithms — Bubble, Merge, Quick & Heap Sort",
        "Searching Algorithms — Binary Search & Hash-Based",
        "Programming Paradigms — Procedural & OOP Concepts",
        "OOP — Classes, Objects, Inheritance & Polymorphism",
        "Database Management — RDBMS, ER Model & Normalisation",
        "SQL — DDL, DML, Queries, Joins & Transactions",
        "Computer Networks — OSI & TCP/IP Reference Models",
        "Network Protocols — HTTP, FTP, SMTP, DNS & TCP/UDP",
        "Internet Architecture — Routing, Switching & VPN",
        "Cybersecurity — Threats, Cryptography & Firewalls",
        "Public Key Infrastructure — RSA, AES & Digital Signatures",
        "Software Engineering — SDLC, Waterfall & Agile",
        "Software Testing — Unit, Integration & System Testing",
        "Artificial Intelligence — Search Algorithms & Expert Systems",
        "Machine Learning — Supervised, Unsupervised & Reinforcement",
        "Cloud Computing — IaaS, PaaS, SaaS & Models",
        "Big Data — Hadoop, MapReduce & Data Analytics",
        "Blockchain — Distributed Ledger & Smart Contracts",
        "Theory of Computation — Automata & Turing Machines",
        "IT in Pakistan — Digital Pakistan Vision & E-Governance",
    ],

    "International Law": [
        "Nature, Definition & Basis of International Law",
        "Sources — Art. 38 ICJ Statute: Treaties, Custom & Principles",
        "History of International Law — Grotius to UN Charter",
        "State — Recognition, Sovereignty & Equality",
        "Territorial Sovereignty — Land, Sea, Air & Space",
        "Law of the Sea — UNCLOS Zones (Territorial, EEZ, High Seas)",
        "Treaties — Vienna Convention 1969 & Treaty Law",
        "International Organisations — Personality & Privileges",
        "UN Charter — Purposes, Principles & Organs",
        "UN Security Council — Powers, Veto & Reform",
        "Use of Force — Art. 2(4), Self-Defence & R2P",
        "UN Peacekeeping — Principles & Pakistan's Contribution",
        "Peaceful Settlement of Disputes — Negotiation to ICJ",
        "International Court of Justice — Jurisdiction & Cases",
        "International Arbitration — PCA & Investor-State",
        "International Human Rights Law — UDHR & Covenants",
        "Regional Human Rights Systems — ECHR & ACHR",
        "International Humanitarian Law — Geneva Conventions",
        "International Criminal Law — ICC, Genocide & War Crimes",
        "Refugee Law — 1951 Refugee Convention & Pakistan",
        "International Environmental Law — Stockholm to Paris",
        "Diplomatic Law — Vienna Convention 1961",
        "Consular Law — Vienna Convention 1963",
        "State Responsibility — ILC Draft Articles",
        "Immunity — State Immunity & Diplomatic Privileges",
        "Right of Self-Determination — Colonial & Post-Colonial",
        "International Trade Law — WTO & GATT",
        "Cyber Law in International Context",
        "Kashmir Issue — International Law Dimensions",
        "Contemporary IL — Climate Change & Pandemic Law",
    ],

    "Muslim Law & Jurisprudence": [
        "Nature, Definition & Scope of Islamic Law (Shariah)",
        "Sources — Quran: Types of Verses & Legal Derivation",
        "Sources — Sunnah: Types, Hadith & Legal Authority",
        "Sources — Ijma (Consensus): Types & Binding Force",
        "Sources — Qiyas (Analogy): Elements & Process",
        "Secondary Sources — Istihsan, Maslaha & Urf",
        "Schools of Jurisprudence — Hanafi School",
        "Schools of Jurisprudence — Maliki, Shafi'i & Hanbali",
        "Maqasid al-Shariah — Objectives & Five Essentials",
        "Islamic Law of Legal Capacity — Ahliyyah",
        "Islamic Family Law — Nikah: Definition, Conditions & Types",
        "Mehr (Dower) — Types, Amount & Legal Status",
        "Divorce — Talaq: Types, Iddat & Legal Effects",
        "Khul & Fasakh — Wife-Initiated Dissolution",
        "Guardianship & Custody — Hadaanah",
        "Islamic Law of Inheritance — Quran, Sunnah & Application",
        "Calculation of Shares — Asabat, Dhawil Arham",
        "Islamic Law of Gifts (Hiba) — Essentials & Revocation",
        "Waqf — Types, Administration & Contemporary Issues",
        "Islamic Contract Law — Elements, Types & Validity",
        "Sale (Bay') — Types, Conditions & Prohibited Transactions",
        "Islamic Finance — Murabaha, Ijara, Musharakah & Mudarabah",
        "Islamic Criminal Law — Hudood Offences",
        "Qisas & Diyat — Retaliation & Blood Money",
        "Ta'zir — Discretionary Punishment",
        "Islamic Constitutional Law — Shura & Rulership",
        "Rights of Non-Muslims in Islamic State",
        "Muslim Personal Law in Pakistan — MFLO 1961",
        "Hudood Ordinances — Provisions & Controversy",
        "Ijtihad vs Taqlid — Reform of Muslim Law",
        "Contemporary Issues — IVF, Organ Donation & Bioethics",
    ],

    "Environmental Science": [
        "Introduction to Environmental Science — Scope & Importance",
        "Ecosystem — Structure, Components & Energy Flow",
        "Food Chains, Food Webs & Ecological Pyramids",
        "Biogeochemical Cycles — Carbon, Nitrogen, Phosphorus & Water",
        "Biodiversity — Levels, Measurement & Value",
        "Threats to Biodiversity — Habitat Loss, Invasive Species",
        "Conservation Strategies — In-Situ & Ex-Situ",
        "Population Ecology — Growth Models & Carrying Capacity",
        "Community Ecology — Succession, Climax & Competition",
        "Air Pollution — Sources, Types, Health Effects & Standards",
        "Water Pollution — Sources, Types, Indicators & Treatment",
        "Soil Pollution, Land Degradation & Remediation",
        "Solid Waste Management — 3Rs & Landfill Issues",
        "Noise & Radiation Pollution",
        "Climate Change — Greenhouse Gases & Mechanism",
        "Evidence & Impacts of Climate Change",
        "Climate Change Mitigation — Renewable Energy & CDM",
        "Climate Change Adaptation — Pakistan Strategies",
        "Ozone Depletion — CFCs, Montreal Protocol",
        "Deforestation — Causes, Consequences & Solutions",
        "Desertification & Land Degradation",
        "Water Resources — Freshwater Scarcity & Management",
        "Renewable Energy — Solar, Wind, Hydro & Biomass",
        "Environmental Legislation in Pakistan — NEPA & NEP",
        "Environmental Impact Assessment — Process",
        "International Conventions — Kyoto, Paris & CBD",
        "UN Sustainable Development Goals — SDG 13, 14, 15",
        "Environmental Ethics — Anthropocentrism vs Ecocentrism",
        "Environmental Issues in Pakistan — Smog, Floods & Drought",
        "Green Economy & Sustainable Development Pathways",
    ],

    "Agriculture & Forestry": [
        "Introduction to Agriculture — Importance & Scope",
        "Soil Science — Composition, Profile & Types",
        "Soil Fertility — Macro & Micronutrients",
        "Soil Degradation, Erosion & Conservation Methods",
        "Crop Physiology — Germination, Growth & Yield",
        "Major Crops of Pakistan — Wheat & Rice Production",
        "Major Crops — Cotton, Sugarcane & Maize",
        "Horticulture — Fruits, Vegetables & Floriculture",
        "Irrigation Systems — Canal, Drip, Sprinkler & Waterlogging",
        "Indus Waters Treaty & Pakistan's Water Challenges",
        "Fertilisers — Types, Application & Environmental Impact",
        "Pesticides — Classes, Overuse, Resistance & IPM",
        "Integrated Pest Management (IPM) — Principles",
        "Plant Diseases — Fungal, Bacterial, Viral & Control",
        "Agricultural Biotechnology & GMO Crops",
        "Livestock — Breeds, Cattle, Dairy & Meat Production",
        "Poultry Farming — Broiler, Layer & Management",
        "Fisheries & Aquaculture in Pakistan",
        "Agricultural Credit — Zarai Taraqiati Bank & Sources",
        "Agricultural Marketing, Value Chain & Supply Chain",
        "Agricultural Policy — NARC, PARC & Recent Reforms",
        "Food Security — Concepts, SDG2 & Pakistan's Status",
        "Climate Change Impacts on Agriculture & Adaptation",
        "Organic Farming — Principles, Certification & Markets",
        "Precision Agriculture — GIS, Drones & Smart Farming",
        "Introduction to Forestry — Forest Types & Ecology",
        "Forest Types in Pakistan — Tropical, Temperate & Alpine",
        "Deforestation in Pakistan — Causes, Scale & Impact",
        "Forest Management & Sustained Yield Principle",
        "Billion Tree Tsunami & Ten Billion Tree Programme",
        "Agroforestry — Benefits & Systems",
    ],

    "Pure Mathematics": [
        "Sets, Relations & Functions — Fundamental Concepts",
        "Mathematical Logic — Propositional & Predicate Calculus",
        "Number Theory — Divisibility, Primes, GCD & Congruences",
        "Real Analysis — Sequences, Limits & Convergence",
        "Real Analysis — Continuity & Uniform Continuity",
        "Differential Calculus — Differentiation Theorems",
        "Integral Calculus — Riemann Integration & Techniques",
        "Sequences & Series of Functions — Uniform Convergence",
        "Complex Numbers — Modulus, Argument & Geometry",
        "Complex Analysis — Analytic Functions & Cauchy-Riemann",
        "Cauchy's Integral Theorem & Formula",
        "Taylor & Laurent Series & Residue Theorem",
        "Linear Algebra — Matrices, Determinants & Systems",
        "Vector Spaces — Subspaces, Basis & Dimension",
        "Linear Transformations, Eigenvalues & Eigenvectors",
        "Inner Product Spaces & Gram-Schmidt Process",
        "Abstract Algebra — Groups, Subgroups & Homomorphisms",
        "Rings, Ideals, Fields & Polynomial Rings",
        "Topology — Metric Spaces, Open & Closed Sets",
        "Topological Spaces — Continuity & Compactness",
        "Ordinary Differential Equations — First Order Methods",
        "ODE — Higher Order & Systems of Equations",
        "Partial Differential Equations — Wave & Heat Equations",
        "Fourier Series & Fourier Transform",
        "Measure Theory — Lebesgue Measure & Integration",
        "Functional Analysis — Normed & Banach Spaces",
        "Hilbert Spaces & Operators",
        "Numerical Analysis — Root Finding & Interpolation",
        "Combinatorics & Graph Theory",
        "CSS Past Paper Pure Mathematics Problems",
    ],

    "Applied Mathematics": [
        "Statics — Forces, Moments, Couples & Equilibrium",
        "Statics — Centre of Gravity & Centroid",
        "Dynamics — Kinematics: Velocity, Acceleration & Graphs",
        "Newton's Laws — Applications & Connected Bodies",
        "Projectile Motion — Equations & Range",
        "Circular Motion — Centripetal Force & Banking",
        "Work, Energy, Power & Conservation Laws",
        "Momentum, Impulse & Collision Types",
        "Simple Harmonic Motion — Pendulum & Spring",
        "Fluid Statics — Pressure, Archimedes & Buoyancy",
        "Fluid Dynamics — Continuity & Bernoulli's Equation",
        "Viscosity, Reynolds Number & Pipe Flow",
        "Electrostatics — Coulomb's Law & Gauss's Law",
        "Magnetostatics — Biot-Savart & Ampere's Law",
        "Electromagnetic Induction & Faraday's Law",
        "Maxwell's Equations — Overview",
        "Classical Mechanics — Lagrangian Formulation",
        "Hamiltonian Mechanics",
        "Operations Research — Linear Programming (Simplex)",
        "OR — Transportation & Assignment Problems",
        "Game Theory — Two-Person Zero-Sum Games",
        "Network Analysis — CPM, PERT & Shortest Path",
        "Mathematical Modelling — Formulation & Solution",
        "Differential Equations in Engineering & Science",
        "Fourier Analysis Applications",
        "Numerical Methods — Euler, Runge-Kutta",
        "Matrix Methods — Eigenvalue Problems",
        "Probability Applications in Applied Mathematics",
        "Queuing Theory — Models & Applications",
        "CSS Past Paper Applied Mathematics Problems",
    ],

    "Gender Studies": [
        "Introduction to Gender — Sex vs Gender Distinction",
        "Feminist Theories — Liberal, Radical & Socialist Feminism",
        "Intersectionality — Race, Class, Gender & Disability",
        "Gender Socialisation — Agents, Processes & Impact",
        "Patriarchy — Concept, Origins & Manifestations",
        "Masculinity Studies — Hegemonic & Multiple Masculinities",
        "Gender & Work — Glass Ceiling, Wage Gap & Segregation",
        "Unpaid Care Work & Domestic Labour",
        "Women's Political Participation — Quotas & Representation",
        "Women in Pakistan — Constitutional & Legal Status",
        "Gender-Based Violence — Definitions & Global Prevalence",
        "Honour Killings — Socio-Legal & Cultural Analysis",
        "Child Marriage — Causes, Consequences & Legislation",
        "Human Trafficking & Sexual Exploitation",
        "Gender & Education — Access, Quality & STEM Gap",
        "Girls' Education in Pakistan — Barriers & Solutions",
        "Gender & Health — Maternal Mortality & Reproductive Rights",
        "Gender & Religion — Quranic Perspectives on Women",
        "Islam & Women's Rights — Reform Discourse",
        "Gender & Development — WID, WAD & GAD Frameworks",
        "UN Women & International Gender Frameworks",
        "CEDAW — Key Provisions & Pakistan's Reservations",
        "SDG 5 — Gender Equality Targets & Progress",
        "Women's Movement in Pakistan — APWA to AURAT March",
        "Gender & Media — Representation, Stereotypes & Objectification",
        "Gender & Environment — Ecofeminism",
        "Gender-Responsive Budgeting & Policy Analysis",
        "Transgender Rights — Legal Recognition & Challenges",
        "Men as Allies — Engaging Men in Gender Equality",
        "Contemporary Feminist Issues in Pakistan",
    ],

    "Criminology": [
        "Definition, Scope & History of Criminology",
        "Classical School — Beccaria, Bentham & Deterrence",
        "Positivist School — Lombroso & Biological Theories",
        "Psychological Theories of Crime — Personality & Psychopathy",
        "Social Disorganisation Theory — Shaw & McKay",
        "Strain & Anomie Theory — Durkheim & Merton",
        "Differential Association — Sutherland's Theory",
        "Social Control Theory — Hirschi's Social Bonding",
        "Labelling Theory — Becker, Stigma & Secondary Deviance",
        "Critical & Conflict Criminology — Marxist Approach",
        "Feminist Criminology — Gender & Crime",
        "Environmental Criminology — Routine Activity Theory",
        "Rational Choice Theory — Cost-Benefit of Crime",
        "Types of Crime — Property, Violent & Public Order",
        "White-Collar & Corporate Crime — Sutherland",
        "Organised Crime — Structures & Transnational Crime",
        "Terrorism — Definitions, Typologies & Radicalisation",
        "Drug Trafficking & Narcotics Control in Pakistan",
        "Cybercrime — Types, Scale & Legal Responses",
        "Juvenile Delinquency — Causes, Patterns & Prevention",
        "Victimology — Victim Precipitation & Victim Rights",
        "Criminal Justice System — Police, Prosecution & Courts",
        "Policing — Community, Problem-Oriented & Intelligence-Led",
        "Sentencing — Principles, Theories & Disparities",
        "Prison & Corrections — Punishment vs Rehabilitation",
        "Probation, Parole & Restorative Justice",
        "Capital Punishment — Debate & Human Rights",
        "Crime Statistics — Official Data vs Dark Figure",
        "Criminal Justice System in Pakistan — Issues",
        "Counter-Terrorism Laws & APS Peshawar Context",
    ],

    "Philosophy": [
        "Introduction to Philosophy — Branches & Methods",
        "Pre-Socratic Philosophers — Thales, Heraclitus & Pythagoras",
        "Socrates — Socratic Method & Trial",
        "Plato — Theory of Forms, The Republic & Epistemology",
        "Aristotle — Logic, Metaphysics, Ethics & Politics",
        "Hellenistic Philosophy — Stoicism, Epicureanism & Scepticism",
        "St. Augustine — Faith & Reason, City of God",
        "Al-Kindi & Al-Farabi — Islamic Neoplatonism",
        "Ibn Sina (Avicenna) — Existence & Essence",
        "Al-Ghazali — Critique of Philosophers",
        "Ibn Rushd (Averroes) — Defence of Philosophy",
        "St. Thomas Aquinas — Natural Law & Five Ways",
        "Descartes — Cogito Ergo Sum & Method of Doubt",
        "Locke — Empiricism, Tabula Rasa & Political Philosophy",
        "Berkeley — Idealism: To Be is to Be Perceived",
        "Hume — Scepticism, Causation & Bundle Theory of Self",
        "Kant — Critique of Pure Reason & Categorical Imperative",
        "Hegel — Dialectics, Absolute Idealism & Philosophy of History",
        "Marx — Historical Materialism & Alienation",
        "Nietzsche — Will to Power, Eternal Return & Nihilism",
        "Logical Positivism — Vienna Circle & Verification Principle",
        "Existentialism — Sartre, Camus & Heidegger",
        "Analytic Philosophy — Russell & Early Wittgenstein",
        "Late Wittgenstein — Language Games & Philosophical Investigations",
        "Post-Modernism — Derrida's Deconstruction & Foucault",
        "Pragmatism — Peirce, James & Dewey",
        "Epistemology — Knowledge, Belief, Justification & Scepticism",
        "Ethics — Utilitarianism, Deontology & Virtue Ethics",
        "Political Philosophy — Justice, Liberty & Rawls",
        "Allama Iqbal's Philosophy — Reconstruction of Religious Thought",
    ],

    "Urdu": [
        "Urdu Language — Origin, Development & Linguistic Features",
        "Classical Poetry — Ghazal: Form, Rules & Masters",
        "Qasida, Marsiya & Masnavi — Forms & Examples",
        "Mir Taqi Mir — Life, Divan & Themes",
        "Mirza Ghalib — Divan-e-Ghalib & Philosophical Depth",
        "Ghalib's Urdu Letters — Khutoot-e-Ghalib",
        "Allama Iqbal — Bang-e-Dra & Early Patriotic Poetry",
        "Iqbal — Baal-e-Jibril, Armaghan-e-Hijaz",
        "Faiz Ahmed Faiz — Naqsh-e-Faryadi & Resistance Poetry",
        "Josh Malihabadi & Noon Meem Rashid",
        "Modern Urdu Nazm — Free Verse & Symbolism",
        "Urdu Prose — History & Development",
        "Early Urdu Novel — Deputy Nazir Ahmed & Hali",
        "Prem Chand — Godan & Urdu Realist Fiction",
        "Qurratul Ain Hyder — Aag ka Darya",
        "Abdullah Hussein — Udas Naslein",
        "Urdu Short Story — Manto's Life & Selected Works",
        "Ismat Chughtai — Feminist Voice & Controversy",
        "Rajinder Singh Bedi & Other Masters",
        "Urdu Drama — Classical Sangeet Natak to Modern",
        "Urdu Essay — Khutoot & Insha-Pardazi Tradition",
        "Urdu Grammar — Noun, Pronoun, Verb & Adjective",
        "Urdu Syntax — Sentence Structures",
        "Idiomatic Urdu — Muhavare & Zarb-ul-Amsal",
        "Translation Skills — Urdu to English & Vice Versa",
        "Urdu Literary Criticism — Theory & Major Critics",
        "Post-1947 Pakistani Urdu Literature",
        "Contemporary Urdu Poetry & Prose",
        "Past Paper Comprehension & Essay Questions",
    ],

    "Arabic": [
        "Arabic Alphabet — Script, Pronunciation & Diacritics",
        "Noun (Ism) — Gender, Number & Definiteness",
        "Verb (Fil) — Root System, Patterns & Conjugation",
        "Particle (Harf) — Prepositions, Conjunctions & Negation",
        "Sentence Structure — Nominal (Jumla Ismiyya)",
        "Sentence Structure — Verbal (Jumla Filiyya)",
        "Idafa Construction & Definite Article",
        "Past Tense (Madi) — All Persons & Forms",
        "Present/Future Tense (Mudari) — All Forms",
        "Imperative, Jussive & Subjunctive Moods",
        "Derived Verb Forms (Awzaan) — Form II to Form X",
        "Broken Plural (Jam' Taksir) — Common Patterns",
        "Sound Plural (Jam' Salim) — Masculine & Feminine",
        "Dual Form — Nouns, Verbs & Pronouns",
        "Adjective Agreement, Comparison & Superlative",
        "Relative Clauses — Relative Pronouns",
        "Conditional Sentences — Types & Usage",
        "Quranic Arabic — Special Features & Vocabulary",
        "Quranic Comprehension — Selected Surahs",
        "Hadith Arabic — Style & Key Vocabulary",
        "Pre-Islamic Poetry — Mu'allaqat & Amr al-Qays",
        "Abbasid Poetry — Al-Mutanabbi & Abu Nuwas",
        "Al-Jahiz & Classical Arabic Prose",
        "Modern Arabic Literature — Naguib Mahfouz",
        "Arabic-Urdu-Persian Language Connections",
        "Translation Exercises — Arabic to Urdu",
        "Composition Writing — Basic Arabic Paragraphs",
        "Nahw Review — Comprehensive Grammar Drill",
        "Sarf Review — Morphology Comprehensive Drill",
        "CSS Past Paper Arabic Questions & Model Answers",
    ],

    "Persian": [
        "Persian Language — History, Script & Phonology",
        "Persian Grammar Basics — Nouns, Gender & Number",
        "Persian Verb System — Root, Infinitive & Stems",
        "Verb Conjugation — Past, Present & Future",
        "Persian Sentence Structure — SOV Pattern",
        "Persian Vocabulary — Common, Formal & Literary",
        "Persian Ezafe Construction",
        "Rumi — Life, Masnavi-e-Manavi & Spiritual Themes",
        "Rumi — Divan-e-Shams-e-Tabrizi: Selected Ghazals",
        "Hafiz Shirazi — Divan-e-Hafiz & Mystical Love Poetry",
        "Saadi Shirazi — Gulistan: Prose Poems & Wisdom",
        "Saadi — Bustan: Ethics & Morality",
        "Firdausi — Shahnameh: Epic Poetry & Persian Identity",
        "Omar Khayyam — Rubaiyat & Philosophical Themes",
        "Nizami Ganjavi — Layla-Majnun & Romantic Epics",
        "Jami — Yusuf & Zulaykha & Classical Tradition",
        "Persian Mysticism (Tasawwuf) in Literature",
        "Persian Historical Prose — Tarikh-e-Firishta",
        "Persian Influence on Urdu & South Asian Literatures",
        "Iqbal's Persian — Asrar-e-Khudi & Rumuz-e-Bekhudi",
        "Iqbal's Persian — Payam-e-Mashriq & Javid Nama",
        "Persian in the Mughal Court & Administrative Use",
        "Ghazal — Persian Form, Rules & Technique",
        "Qasida — Panegyric Form & Major Examples",
        "Modern Persian — Iran, Afghanistan (Dari) & Tajikistan",
        "Translation Practice — Persian to Urdu",
        "Reading Comprehension — Classical Persian Texts",
        "Grammar Review — Comprehensive Drill",
        "CSS Past Paper Persian Questions & Model Answers",
    ],
}

GENERIC_TOPICS = [
    "Fundamental Concepts & Definitions",
    "Theoretical Framework",
    "Historical Development",
    "Key Principles & Doctrines",
    "Major Schools of Thought",
    "Practical Applications",
    "Current Trends & Issues",
    "Research Methodologies",
    "Critical Analysis",
    "Case Studies",
    "Comparative Studies",
    "Contemporary Challenges",
    "Problem-Solving Approach",
    "Advanced Concepts",
    "Revision & Synthesis",
]

CSS_SUBJECTS = (
    ["Essay", "English (Precis & Composition)", "General Science & Ability",
     "Pakistan Affairs", "Islamic Studies", "Current Affairs"]
    + [s for s in SUBJECT_TOPICS if s not in
       ["Essay", "English (Precis & Composition)", "General Science & Ability",
        "Pakistan Affairs", "Islamic Studies", "Current Affairs"]]
)


def _get_topics(subject: str) -> list[str]:
    return SUBJECT_TOPICS.get(subject, [f"{t} in {subject}" for t in GENERIC_TOPICS])


def _get_task_templates(subject: str, proficiency: str) -> list[str]:
    if subject in _WRITING_SUBJECTS:
        pool = _WRITING_TASKS
    elif subject in _NUMERICAL_SUBJECTS:
        pool = _NUMERICAL_TASKS
    elif subject in _LANGUAGE_SUBJECTS:
        pool = _LANGUAGE_TASKS
    else:
        pool = _ANALYTICAL_TASKS
    return pool.get(proficiency, pool["Intermediate"])


def _make_tasks(topic: str, proficiency: str, subject: str) -> str:
    templates = _get_task_templates(subject, proficiency)
    chosen = random.sample(templates, min(2, len(templates)))
    return " | ".join(t.format(topic=topic) for t in chosen)


# ── Plan generator ────────────────────────────────────────────────────────────
class PlanRequest(BaseModel):
    exam_date: date
    proficiency: str = "Intermediate"
    subjects: list[str]
    weak_subject: Optional[str] = None
    hours_per_day: int = 5


@router.post("/generate")
def generate_plan(data: PlanRequest, user: User | None = Depends(get_optional_user)):
    today = date.today()
    if data.exam_date <= today:
        return {"error": "Exam date must be in the future", "days": []}

    total_days = (data.exam_date - today).days
    subjects = [s for s in data.subjects if s]
    if not subjects:
        return {"error": "Select at least one subject", "days": []}

    # Weighted rotation — weak subject gets 1.5× slots
    weighted: list[str] = []
    for s in subjects:
        weight = 3 if s == data.weak_subject else 2
        weighted.extend([s] * weight)

    # Reserve last 10 % for revision (min 3 days)
    revision_days = max(3, total_days // 10)
    study_days = total_days - revision_days

    # Build rotation queue
    rotation: list[str] = []
    while len(rotation) < study_days:
        batch = weighted[:]
        random.shuffle(batch)
        rotation.extend(batch)
    rotation = rotation[:study_days]

    # Topic pointer per subject (modulo cycling so plans never run dry)
    topic_ptr: dict[str, int] = {s: 0 for s in subjects}
    all_topics: dict[str, list[str]] = {s: _get_topics(s) for s in subjects}

    days_output: list[dict] = []
    current = today

    for day_num, subject in enumerate(rotation, start=1):
        topics_for_subject = all_topics[subject]
        n = len(topics_for_subject)
        ptr = topic_ptr[subject]
        # Cycle: second pass marks topics as Revision
        is_revision_round = ptr >= n
        actual_ptr = ptr % n
        # Pick 1 or 2 consecutive topics
        take = 2 if (n - actual_ptr) > 4 and not is_revision_round else 1
        day_topics = topics_for_subject[actual_ptr: actual_ptr + take]
        topic_ptr[subject] += take

        topic_label = " + ".join(day_topics)
        if is_revision_round:
            topic_label = "Revision — " + topic_label

        tasks = _make_tasks(day_topics[0], data.proficiency, subject)

        days_output.append({
            "day":     day_num,
            "date":    current.isoformat(),
            "subject": subject,
            "topic":   topic_label,
            "hours":   data.hours_per_day,
            "tasks":   tasks,
            "done":    False,
        })
        current += timedelta(days=1)

    # Revision days — cycle through subjects, specific topic each day
    rev_cycle = (subjects * (revision_days // max(len(subjects), 1) + 1))[:revision_days]
    for i, rev_subj in enumerate(rev_cycle):
        subj_topics = all_topics[rev_subj]
        # Pick a topic from the second half for targeted revision
        rev_idx = random.randint(max(0, len(subj_topics) // 2), len(subj_topics) - 1)
        rev_topic = subj_topics[rev_idx]
        activity = random.choice(_REVISION_ACTIVITY_SETS)
        days_output.append({
            "day":     study_days + i + 1,
            "date":    current.isoformat(),
            "subject": rev_subj,
            "topic":   f"Final Revision — {rev_topic}",
            "hours":   data.hours_per_day,
            "tasks":   activity,
            "done":    False,
        })
        current += timedelta(days=1)

    total_hours = sum(d["hours"] for d in days_output)
    topic_count = len({d["topic"] for d in days_output})

    return {
        "days":  days_output,
        "stats": {
            "total_days":  len(days_output),
            "total_hours": total_hours,
            "topic_count": topic_count,
            "exam_date":   data.exam_date.isoformat(),
            "subjects":    subjects,
        },
    }


@router.get("/subjects")
def all_subjects():
    return CSS_SUBJECTS


@router.get("/calendar")
def calendar():
    return MONTHLY_PLAN


@router.get("/milestones")
def milestones():
    return [
        {"subject": s, "milestones": [
            "Complete full syllabus reading",
            "Summarise key concepts",
            "Solve MCQs & practice questions",
            "Attempt past-year questions",
            "Full revision & mock test",
        ]}
        for s in CSS_SUBJECTS
    ]
